### ISSUE TITLE
Close/max/minimize buttons too much big and colourful

### ISSUE THREAD

**Issue by josineto** [wfpaisa/plane-theme#10]
Hi! I use this theme (dark variant) since I switched to Manjaro, last June. It's elegant and doesn't clutter the UI with too much colors and details.... **Until last update (3.36)** which turns close, maximize and minimize buttons into giant, annoying colourful circles. And the colors mimic (or try to) MacOS's appearance.

Sincerely, if I wanted to mimic MacOS in Manjaro, I would search for a theme designed specifically for that. *Not yours*. So, please, revert those buttons to earlier versions, or create a variant without those giant colourful circles. Please!

**Comment by Trikenstein** [comment]
Partially agreed on the macOS copycat trend. Why would any theme try to imitate those mac buttons? I have a macbook pro for work. But When I am on Linux, I find those mac imitations rather naive. Anyone craving for mac, well just buy a mac!

On the other hand, I like a lot the big window control buttons. It's more visible on hires monitors.

I also like the colorful buttons. Although not the overkill mac like that. Why? Because the entire window is dark now, when several windows overlap, it's hard to tell the difference. Those buttons help to recognize the top of the window behind.

**Comment by wfpaisa** [comment]
Hi, thanks for writing, I understand that you don't like the button styles.
My decision to change the styles takes some time of research, I made a survey and the vast majority liked more the OSX button style, the most downloaded themes are OSX-like, but I repeat your point of view is valid.
I want to create a tool where you can choose the type of button to use, but this tool may take me a while to create.
Thanks again for taking the time to write.

**Comment by Trikenstein** [comment]
@wfpaisa Not sure who you answered to. But I'm fine with the window control buttons. I like them big, colors are OK. And BTW, you design whatever you feel like. Please don't be concerned by those subjective opinions.

My opinion above about mac-like style was that people's opinion about fashion is not always reliable. It's mostly a herd copycat phenomenon. Like the baggy pants or the worn out jeans full of holes, which strangely enough, are quite expensive. There are people craving for those pants. They just want to belong to the imaginary social status. I guess it's the same for the mac-like GUI. I think people feel more secured when choosing what others like.
