### ISSUE TITLE
Reduce spaces between window title buttons 

### ISSUE THREAD

**Issue by vantu5z** [wfpaisa/plane-theme#4]
I think it will be look sightly with reduced spaces between title buttons, like this:
Before:
![2018-10-23 12-51-01](https://user-images.githubusercontent.com/8698003/47353264-7c2c1d00-d6c4-11e8-800b-afbb5bf885ad.png)
After:
![2018-10-23 12-51-01](https://user-images.githubusercontent.com/8698003/47353295-8e0dc000-d6c4-11e8-805c-4f7b5b9743ed.png)

Looks like that only Nautilus problem.

And another issue but seems it connected. Minimal height of window title bar.
Now it set to 28 but it looks huge for windows without additional buttons (terminal for example).
Now:
![2018-10-23 13-43-32](https://user-images.githubusercontent.com/8698003/47355500-2eb2ae80-d6ca-11e8-8867-fd392a80b801.png)
Suggestion:
![2018-10-23 13-44-32](https://user-images.githubusercontent.com/8698003/47355504-32463580-d6ca-11e8-927e-ee503d64e457.png)

**Comment by wfpaisa** [comment]
I reduced a little bit, no much because is necessary in touch screens

![deepinscreenshot_select-area_20181031094217](https://user-images.githubusercontent.com/1735752/47795873-45bc5680-dcf1-11e8-8bbd-27aa9b57563d.png)

https://github.com/wfpaisa/plane-theme/commit/f287096d79a5e2a2dd6c484a0376f4b3b771d6c1
